--
-- Title: daily_score.psql
-- Description: daily activity summary
--
-- crate_name is crateName (from json)
-- file_quantity is total daily files
-- host_name is from equipment.hostName
-- quantity_adsb is total daily adsb observations
-- quantity_adsb is total daily uat observations
-- score_uat is summary date
--
create table capybara_daily_score (
  id              bigserial    primary key,
  crate_name      varchar(32)  not null,
  file_quantity   integer      not null,
  host_name       varchar(16)  not null,
  quantity_acars  integer      not null,
  quantity_vdl2   integer      not null,
  score_date      date         not null
);

grant select, insert, update, delete on capybara_daily_score to capybara_client;
grant usage, select on sequence capybara_daily_score_id_seq to capybara_client;

create unique index capybara_daily_score_ndx1 on capybara_daily_score(crate_name, host_name, score_date);
