--
-- Title: frequency.psql
-- Description: daily frequency summary
--
-- crate_name is crateName (from json)
-- frequency is observed intercept frequency in hz
-- host_name is from equipment.hostName
-- message_quantity daily message count for frequency
-- mode is from job.mode
-- score_date is summary date
--
create table capybara_frequency (
  id                bigserial    primary key,
  crate_name        varchar(32)  not null,
  frequency         integer      not null,
  host_name         varchar(16)  not null,
  message_quantity  integer      not null,
  mode              varchar(16)  not null,
  score_date        date         not null
);

grant select, insert, update, delete on capybara_frequency to capybara_client;
grant usage, select on sequence capybara_frequency_id_seq to capybara_client;

create unique index capybara_freq_ndx1 on capybara_daily_score(crate_name, host_name, mode, score_date);
